### ISSUE TITLE
chore: remove upstream dependencies

### ISSUE THREAD

**Issue by fbac** [zeta-chain/ethermint#85]
Remove upstream ethermint dependencies and rely solely on zeta-chain/ethermint codebase.

Ideally we'd shift away from evmos/ethermint. Why are we using evmos/ethermint instead of our own types from types/encoding.go, which also export EncodingConfig?

_Originally posted by @fbac in https://github.com/zeta-chain/ethermint/pull/83#discussion_r1689134409_

**Comment by gartnera** [comment]
We're not importing github.com/evmos/ethermint, that's the current name of this module.

We'd need to rename the module and [change the replace in node](https://github.com/zeta-chain/node/blob/develop/go.mod#L363)
