### ISSUE TITLE
Upgrade go-ethereum

### ISSUE THREAD

**Issue by gartnera** [zeta-chain/ethermint#86]
I have a branch where I've upgraded go-ethereum to 1.12.1: https://github.com/zeta-chain/ethermint/tree/upgrade-go-ethereum

We cannot upgrade any further because of:
- https://github.com/ethereum/go-ethereum/pull/27909
- https://github.com/cosmos/cosmos-sdk/issues/20159

We'd need to update our go-ethereum fork to 1.12 and cherry pick the precompiled contract changes again.

**Comment by swift1337** [comment]
@gartnera  https://github.com/cosmos/cosmos-sdk/issues/20159#issuecomment-2287000354 🔥
